# version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: boop-postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: boop
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}?schema=public
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '${LOCAL_PORT}:${PORT}'
    container_name: boop-app

volumes:
  db-data:
