export const metadata = {
  title: 'Swagger Docs',
  description: 'Generated by OpenAPI',
};

export default function SwaggerLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
